name: Build Realme C35 Kernel

on:
  workflow_dispatch: # Кнопка ручного запуска

jobs:
  build-kernel:
    runs-on: ubuntu-22.04

    steps:
    - name: Free Disk Space
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true
        android: true
        dotnet: true
        haskell: true
        large-packages: true

    - name: Checkout Kernel Source
      uses: actions/checkout@v4
      with:
        ref: dev # Собираем именно ветку dev

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git ccache automake flex lzop bison gperf build-essential zip curl zlib1g-dev libc6-dev libssl-dev bc dwarves liblz4-tool

    - name: Download Clang Toolchain
      run: |
        # Скачиваем Clang на один уровень выше, как требует export.env проекта
        git clone https://googlesource.com --depth=1 ../clang
        
    - name: Set Execution Permissions
      run: chmod +x build.sh

    - name: Configure Kernel (KSU + SUSFS)
      run: ./build.sh config-ksu-susfs

    - name: Compile Kernel
      run: ./build.sh compile

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Realme-C35-Kernel-Output
        path: |
          out/arch/arm64/boot/Image.gz
          out/arch/arm64/boot/Image
          out/kernel_log.log
